### ISSUE TITLE
[request] Пресс-релизы

### ISSUE THREAD

**Issue by TorinAsakura** [torin-asakura/ftc#10]
В течение июля нужно сделать по записи для каждого релиза, хотя бы до 1000 символов, просто и лаконично: 
- что легло в основу релиза
- каков был посыл
- какие эмоции стояли за написанием релиза
- что сподвигло
итд

**Comment by fruktoviy** [comment]
FIRST FLIGHT

First Flight – первый альбом Follow The Compass, вышедший в 2012 году. Тогда это был сольный проект бас-гитариста Александра Мухина. 

Как и многие другие студенты, основатель проекта FTC играл в группах, исполняя партии различных рок-песен на бас-гитаре. Позже друзья перестали собираться, что послужило началу нового этапа в творчестве.

Уже в 2011 году Саша стал придумывать свой материал. Композиции были вдохновлены путешествиями на природу: в лес, на озера и море — после таких впечатлений музыка приходила сама собой. Придуманные мелодии были «подслушаны» близкими друзьями и родными, и по их совету было решено записывать альбом. Через некоторое время, 22 апреля 2012 года, альбом увидел свет. 

LOOKING FORWARD

После успешного первого релиза Александру захотелось внести в свое творчество больше разнообразия, и он стал искать человека, близкого по мироощущению, который сможет подыграть ему на клавишных. Уже летом 2012 года к проекту присоединилась Дарья Пчелинцева. Она добавила клавиши в уже имеющиеся композиции, и при ее участии был записан этот EP. Он состоит из трех летних композиций — Summer, Looking Forward и July Sun (ссылка на видео), на которую было снято видео в парке 300-летия Санкт-Петербурга.

В основу этого EP была положена идея светлого взгляда в будущее, а вдохновение пришло в прекрасную летнюю погоду.

STAY WITH ME (СИНГЛ)

Это переиздание композиции Stay With Me из альбома First Flight. Заглавная мелодия из фильма «Фонтан» вдохновила нас на создание столь красивого трека. Это наша импровизация на основе полюбившейся медодии. Также в данный релиз входит композиция с новогодним настроением — Christmas.

После реализации этого сингла, первых концертов в Москве и Петербурге и спустя год совместного творчества Дарья Пчелинцева покинула проект, и Александр начал искать нового клавишника.

SIRENS (СИНГЛ)

Зимой 2014 года Дарья познакомила Александра с Ксенией, которая училась вместе с ней в университете на курсе звукорежиссуры. Музыканты быстро нашли общий язык, и создали «пробную» композицию Sirens. Трек был записан дома и сведен Ксенией. Весь процесс произошел буквально за пару дней.

Поняв, что им по пути, сразу после данного релиза ребята активно начали работать над новым полноценным альбомом. 

IMAGINATION

Это первая студийная работа, и второй альбом Follow The Compass. Все композиции были записаны на уютной студии «Библиотека Им.» зимой 2014 года, сам же альбом был реализован в июле того же года. 

В новом релизе звучание стало более красочным за счет появления свежих идей и инструментов: во вступлении трека Mountains звучит хруст снега Уральских гор, в Close your eyes можно услышать вокализ и скрипку, Gale Warning содержит пение китов, в Lunar Eclipse использованы звуки планет. Трек Empty является одним из самых грустных — с этим связано появление звуков большого города. Также в композиции использована губная гармошка и живой ритм барабанов ближе к концу трека.

INSIDE

Альбом Inside вышел 20 апреля 2016 года. Мы сделали его более чувственным и глубоким, стараясь открыть все грани того, что есть внутри каждого из нас. Обложка альбома призвана подчеркнуть основную мысль релиза. 

Из интересных наработок: заглавная композиция Inside была записана с помощью нового для Саши инструмента — безладовой бас-гитары, в треке Between The Lines звучит африканский музыкальный инструмент калимба, в Canyon – индейская этническая флейта пимак, в Other Places – пение кавказских горных птиц. Также в Intestellar Theme – нашем варианте исполнения заглавного трека к одноименному фильму — мы записали хоровое пение. 

На композицию One moment (ссылка на видео) было снято атмосферное видео на берегу Финского залива. Идея — ценить настоящий момент, каким бы он ни был.

RETURN (СИНГЛ)

Наша первая композиция, где можно услышать полноценное живое звучание виолончели, а также безладовой бас-гитары в основе мелодии. Входе подготовки к предстоящим концертам в поддержку релиза Inside участники проекта познакомились с Валерией, профессиональной виолончелисткой. Лера поразила ребят своим умением схватывать все на лету, ее идеи им очень понравились. Отыграв концерты в Москве и в Петербурге как трио, музыканты пригласили Валерию в состав группы, а позже — записали композицию Return.
Также вместе с данным синглом выпущено урбанистическое видео (ссылка на видео) с высоты птичьего полета над прекрасным городом Санкт-Петербург.

COLORS (СИНГЛ)

Летом 2019 года мы выпустили умиротворяющее видео на композицию Colors (ссылка на видео), которая является синглом к одноименному альбому. Мелодия призвана погрузить вас в атмосферу морских пейзажей и путешествий. 
Довольно часто в проекте FTC мелодии рождаются с ходу, Colors не исключение!

COLORS

21 октября 2019 года вышел самый свежий релиз Follow The Compass. Этот альбом является логичным продолжением предыдущего — Inside. 
Colors очень разный по настроению и гамме эмоций, но объединяет эти композиции искренность. Этот альбом содержит большое количество мелодий, носящих личный характер: поддержка и потеря близких людей, неизведанное будущее, а также появление новых спутников.
Интересные факты: трек Aurora Lights был придуман на студии, когда уже все композиции были записаны, в Sputnik можно услышать реальные переговоры космонавтов, в Tomorrow впервые была использована акустическая гитара, а в Marianna звучат детские голоса.

**Comment by fruktoviy** [comment]
FIRST FLIGHT

First Flight is the first Follow The Compass album, released in 2012. It was entirely a solo project of bassist Alexander (Sasha) Mukhin.

Prior to that, like many other musically inclined college students, Alexander, the founder of the FTC, performed with multiple rock bands as a bass player.  After some time, these bands broke up, and that left him with the prospects of launching a solo project.

In 2011, Sasha became serious about music composing.  His compositions were inspired by hiking trips, nature walks, forests, lakes and the sea coast.  The impressions took shape in the form of music. The new creations were "overheard" by close friends and family.  Encouraged by their reaction, he recorded First Flight, which was released a few months later in 2012, on April 22 ( Lenin’s birthday).




LOOKING FORWARD

Following up the debut album, Alexander wanted to add more variety to his work, and started looking for a like-minded collaborator to join him on keyboards.  In the summer of 2012 Ms. Daria Pchelintseva joined the project.  She added keyboard parts to the finished music pieces, and recorded them on Looking Forward EP.  There are three compositions - Summer, Looking Forward and July Sun (link to video).  The video was shot in the St. Petersburg Tricentennial Park.

The EP’s  key message of ​​brighter outlook was inspired by beautiful summer weather.


STAY WITH ME (СИНГЛ)

Это переиздание композиции Stay With Me из альбома First Flight. Заглавная мелодия из фильма «Фонтан» вдохновила нас на создание столь красивого трека. Это наша импровизация на основе полюбившейся медодии. Также в данный релиз входит композиция с новогодним настроением — Christmas.

После реализации этого сингла, первых концертов в Москве и Петербурге и спустя год совместного творчества Дарья Пчелинцева покинула проект, и Александр начал искать нового клавишника.





SIRENS (СИНГЛ)

In the winter of 2014, Daria introduced Alexander to her college classmate Ms. Ksenia who was a keyboard player and also majored in audio production.  They quickly found a common ground and put together a "trial" track Sirens. It was home-recorded and later mixed by Ksenia. The whole process took literally two days.

Right after they completed the track, it became clear that they get along really well, so they pressed  on to complete a full-scale album.

IMAGINATION

In the winter of 2014 Follow The Compass recorded its sophomore album using for the first time a professional studio, cozy and friendly "Biblioteka Im." The album was released in July of 2014.

The sound on this new release was more colorful enriched by fresh ideas and new instruments: the intro of Mountains, features the sample of  snow crunching in the Ural mountains, there is vocalese and violin in Close Your Eyes, Gale Warning has whales, and Lunar Eclipse has planetary sounds.  The most melancholic track Empty features city soundscapes, harmonica and live drums.





INSIDE
The album was released on April 20, 2016. It emphasized sensuality and depth in attempt to reveal all the facets of the musicians’ inner world. The album cover visually reflects its key message.

Among new approaches, the title track Inside was laid down by Sasha playing a fretless bass, African instrument kalimba is used in Between The Lines, a flute from India,  pimak, is featured on Canyon, and the of Caucasian mountain bird songs from the Caucasus mountains on the Other Places.  Also, there is choir singing in Intestellar Theme, FTC’s take on the title track for the 2014 film of the same name.

The video for One moment (link to video) was shot on the shores of the Gulf of Finland. Its main idea is the appreciation of the present moment, whatever it may be.






RETURN (СИНГЛ)  DATE
This composition introduced cello into the mix while fretless bassline forms the foundation of the tune.  While preparing for the performances promoting the release of Inside, the two project members met Valeria (Lera), who is a professionally trained cello player. She impressed the project members with her quick-learning skills, they also liked some of her ideas.  Then, after FTC played several shows in Moscow and St. Petersburg as a trio, Valeria was officially invited to the group. Return was the first fruit of this collaboration.
The urban landscape video (link to the video) for the track shows bird's eye view of beautiful St. Petersburg.


COLORS (SINGLE)

The video for the track was released in the summer of 2019, was intended to have a calming effect. The tune is an immersion into the atmosphere of seascapes and voyages.
It is common for the FTC project to create new tunes, on the fly, Colors is one of them.

COLORS

The latest Follow The Compass album was released on October 21, 2019.  This is a follow up to Inside, and while it differs in mood and in range of emotions, on thing both albums have in common is sincerity. Many tunes on the album are informed by personal lives of the project members: support and loss of loved ones, future unknown, and new fellow travelers joining in. 
Aurora Lights was born at the studio during the last recording session after all other tracks were finished.  Sputnik features recordings of Russian cosmonauts’ radio communications.  Tomorrow introduced acoustic guitar into the mix, and voices of children were recorded for Marianna.

**Comment by fruktoviy** [comment]
FIRST FLIGHT

First Flight is the first Follow The Compass album, released in 2012. It was entirely a solo project of bassist Alexander (Sasha) Mukhin.

Prior to that, like many other musically inclined college students, Alexander, the founder of the FTC, performed with multiple rock bands as a bass player.  After some time, these bands broke up, and that left him with the prospects of launching a solo project.

In 2011, Sasha became serious about music composing.  His compositions were inspired by hiking trips, nature walks, forests, lakes and the sea coast.  The impressions took shape in the form of music. The new creations were "overheard" by close friends and family.  Encouraged by their reaction, he recorded First Flight, which was released a few months later in 2012, on April 22.


LOOKING FORWARD

Following up the debut album, Alexander wanted to add more variety to his work, and started looking for a like-minded collaborator to join him on keyboards.  In the summer of 2012 Ms. Daria Pchelintseva joined the project.  She added keyboard parts to the finished music pieces, and recorded them on Looking Forward EP.  There are three compositions - Summer, Looking Forward and July Sun (link to video).  The video was shot in the St. Petersburg Tricentennial Park.

The EP’s key message of brighter outlook was inspired by beautiful summer weather.


STAY WITH ME (SINGLE)

This is a reissue of Stay With Me from the First Flight album. The main theme from the movie Fountain composed by Clint Mansell served as an inspiration for this track. This is FTC’s improvisation based on the memorable tune.  There is also a Happy New Year-themed composition Christmas on the same release.

After a year of  collaboration through the completion of this single, and a series of shows in Moscow and St. Petersburg, Daria Pchelintseva left and  Alexander started looking for a keyboard player to replace her.




SIRENS (SINGLE)

In the winter of 2014, Daria introduced Alexander to her college classmate Ms. Ksenia who was a keyboard player and also majored in audio production.  They quickly found a common ground and put together a "trial" track Sirens. It was home-recorded and later mixed by Ksenia. The whole process took literally two days.

Right after they completed the track, it became clear that they quickly gelled, so they pressed  on to complete a full-scale album.

IMAGINATION

In the winter of 2014 Follow The Compass recorded its sophomore album using for the first time a professional studio, cozy and friendly "Biblioteka Im."  The album was released in July of 2014.

The sound on this new release was more colorful enriched by fresh ideas and new instruments: the intro of Mountains, features the sample of snow crunching in the Ural mountains, there is vocalese and violin in Close Your Eyes, Gale Warning has whales, and Lunar Eclipse has planetary sounds.  The most melancholic track Empty features city soundscapes, harmonica and live drums.





INSIDE

The album was released on April 20, 2016. It emphasized sensuality and depth in attempt to reveal all the facets of the musicians’ inner world. The album cover visually reflects its key message.

Among new approaches, the title track Inside was laid down by Sasha playing a fretless bass, African instrument kalimba is used in Between The Lines, a flute from India,  pimak, is featured on Canyon, and the of Caucasian mountain bird songs from the Caucasus mountains on the Other Places.  Also, there is choir singing in Intestellar Theme, FTC’s take on the the soundtrack by Hanz Zimmer for the 2014 film of the same name.

The video for One Moment (link to video) was shot on the shores of the Gulf of Finland. Its main idea is the appreciation of the present moment, whatever it may be.



RETURN (SINGLE) 

This composition introduced cello into the mix while fretless bass creates the foundation for the tune.  While preparing for the performances promoting the release of Inside, the two project members met Valeria (Lera), who is a professionally trained cello player. She impressed the project members with her quick-learning skills, and her original ideas and suggestions.  Then, after FTC played several shows in Moscow and St. Petersburg as a trio, Valeria was officially invited to join the group.  Return was the first fruit of this collaboration.

The urban landscape video (link to the video) for the track shows bird's eye view of beautiful St. Petersburg.


COLORS (SINGLE)

The video for the track was released in the summer of 2019, was intended to have a calming effect. The tune is an immersion into the atmosphere of seascapes and voyages.
It is common for the FTC project to create new tunes, on the fly, Colors is one of them.



COLORS

The latest Follow The Compass album was released on October 21, 2019.  This is a follow up to Inside, and while it differs in mood and in range of emotions, one thing both albums have in common is sincerity. Many tunes on the album are informed by personal lives of the project members: support and loss of loved ones, future unknown, and new fellow travelers joining in.
 
Aurora Lights was born at the studio during the last recording session after all other tracks were finished.  Sputnik features recordings of Russian cosmonauts’ radio communications.  Tomorrow introduced acoustic guitar into the mix, and voices of children were recorded for Marianna.

**Comment by TorinAsakura** [comment]
@fruktoviy 

По замечаниям
- проверяйте грамматику, пунктуацию, опечатки текстов - несколько ошибок почти в каждом тексте, опечатки
- https://followthecompass.ru/relizy/looking-forward/ - найди нормальный ковер в хайресе, очень низкое качество
- релизы можешь создавать самостоятельно теперь, там всё настроено

По правкам
- немного подкорректировал визуальную часть страницы релизов https://followthecompass.ru/relizy
- новый дизайн для релизов, если бы ещё к релизам были видео - было бы шикарно

За сим завершаю задачу
