### ISSUE TITLE
Правка

### ISSUE THREAD

**Issue by fruktoviy** [torin-asakura/ftc#12]
в разделе Релизы нужно изменить - "LOOKING FORWARD (SINGLE)" на "LOOKING FORWARD (EP)"

**Comment by TorinAsakura** [comment]
Не, ят конечно поменял, вот только у нас даже на Apple Music статус сингла) А так, ты можешь сам всё теперь менять через админку.

![Снимок экрана (14)](https://user-images.githubusercontent.com/3940885/87036537-9fc62c80-c1f3-11ea-958b-19ff6ef7551f.png)
