### ISSUE TITLE
Правки

### ISSUE THREAD

**Issue by fruktoviy** [torin-asakura/ftc#13]
в мобильной версии 
- в Eng версии в разделе release - подраздел ВСЕ, вместо ALL
- в обоих версиях eng/ru в разделе About/О Проекте нет описания (ну это наверное потому что ты там что-то делаешь))

исчезли ссылки на vk, facebook, ins, soundcloud (на оф страницы) 
может стоить добавить их в раздел контакты? или также сделать раздел внизу каждой страницы, как было раньше)

**Comment by TorinAsakura** [comment]
@fruktoviy я посмотрел документацию Yandex Maps API, и пожалуй страницу контактов пока отложу до конца месяца)
По страница всё сделал
Есть ссылка на артиста в VK, а там и до паблика рукой подать.
Facebook, Ins, Soundcloud не приоритетны, люди слушают музыку, а не читают.
Я добавлю всё вторичное добро когда страницу с контактами рожу.
