### ISSUE TITLE
Aurora Lights (video + photo preview)

### ISSUE THREAD

**Issue by fruktoviy** [torin-asakura/ftc#14]
@TorinAsakura 

Photo preview - https://yadi.sk/i/2CwwRXz6I3A59A

Видео будет в понедельник (5 октября)
Прикреплю ссылку в новом сообщении

**Comment by fruktoviy** [comment]
видео - 
https://youtu.be/Sbo5aDOLN9Y

Сегодня в 20:00 по мск будет доступно по ссылке выше!

**Comment by TorinAsakura** [comment]
https://followthecompass.ru/en/videos/
