### ISSUE TITLE
новое видео 

### ISSUE THREAD

**Issue by fruktoviy** [torin-asakura/ftc#15]
сегодня вечером после 19 часов будет доступно по ссылке - https://youtu.be/Om6i1PR1x18

нужно добавить просто в раздел видео, наверное.. не нужно добавлять его на главную страницу.

**Comment by TorinAsakura** [comment]
@fruktoviy это всё круто Сань, только ты не прислал обложку для видео, без обложки чуда не будет

**Comment by TorinAsakura** [comment]
@fruktoviy на будущее - ты можешь их сам добавлять (уже как год) в админке, кнопочками)
