### ISSUE TITLE
ссылки на релизы

### ISSUE THREAD

**Issue by fruktoviy** [torin-asakura/ftc#17]
1 - https://followthecompass.ru/en/release/return-single/
приводит на релиз Colors, а не на Return (все ссылки.. кроме bandcamp)

2 - https://followthecompass.ru/en/release/sirens-single/
ссылки приводят на альбом First Flight!

3 - https://followthecompass.ru/en/release/looking-forward-single/
ссылки приводят на альбом First Flight!

**Comment by TorinAsakura** [comment]
@fruktoviy https://followthecompass.bandcamp.com/album/home-recording - нужно переименовать в sirens

**Comment by TorinAsakura** [comment]
Done
https://followthecompass.ru/en/release/return-single/
https://followthecompass.ru/en/release/sirens-single/
https://followthecompass.ru/en/release/looking-forward-single/
