### ISSUE TITLE
новое видео 

### ISSUE THREAD

**Issue by fruktoviy** [torin-asakura/ftc#18]
ссылка - https://youtu.be/EddNnyBDrxs
нужно добавить в раздел видео на сайт. 
желательно сегодня. видео будет доступно с 20:00 (выложено на ютюб)

**Comment by TorinAsakura** [comment]
> ссылка - https://youtu.be/EddNnyBDrxs
> нужно добавить в раздел видео на сайт.
> желательно сегодня. видео будет доступно с 20:00 (выложено на ютюб)

https://followthecompass.ru
https://followthecompass.ru/videos/
