### ISSUE TITLE
Можно добавить на сайт фото

### ISSUE THREAD

**Issue by fruktoviy** [torin-asakura/ftc#19]
1 - https://disk.yandex.ru/d/nrlIq97clJX1RQ
2 - https://disk.yandex.ru/d/a5HdGl5BKlFtGA
3 - https://disk.yandex.ru/d/m694ttnqMcZmvw
4 - https://disk.yandex.ru/d/Zca6ZRoK7ip8bg
5 - https://disk.yandex.ru/d/ElfyeZDGYGzMpg

эти фотографии были в постах и соц сетях, но на сайте еще не появлялись.  можно добавить их)
на счет фото - 09.20 - Place сомнения) может сделать ее чб? а то слишком плохой цвет)

**Comment by TorinAsakura** [comment]
> 1 - https://disk.yandex.ru/d/nrlIq97clJX1RQ
> 2 - https://disk.yandex.ru/d/a5HdGl5BKlFtGA
> 3 - https://disk.yandex.ru/d/m694ttnqMcZmvw
> 4 - https://disk.yandex.ru/d/Zca6ZRoK7ip8bg
> 5 - https://disk.yandex.ru/d/ElfyeZDGYGzMpg
> 
> эти фотографии были в постах и соц сетях, но на сайте еще не появлялись. можно добавить их)
> на счет фото - 09.20 - Place сомнения) может сделать ее чб? а то слишком плохой цвет)

RAW этих фоток есть?

**Comment by fruktoviy** [comment]
Нет

**Comment by fruktoviy** [comment]
Попробую разобраться
