### ISSUE TITLE
Кнопка переключения на Eng 

### ISSUE THREAD

**Issue by fruktoviy** [torin-asakura/ftc#2]
Нужно будет сделать как раньше - добавить возможность менять язык на сайте. 
Мне уже писали на facebook о то что не переключиться на eng люди из Европы. 

Ссылки на эпл все работают - спасибо :)

**Comment by TorinAsakura** [comment]
@fruktoviy я этот функционал не просто так убрал, нужно было понять пользуются ли этим в действительности - как видно - да

**Comment by fruktoviy** [comment]
надо тогда будет допилить eng.)

**Comment by TorinAsakura** [comment]
надо, но не сейчас

**Comment by TorinAsakura** [comment]
@fruktoviy 

Перевод сюда закинь для страницы https://followthecompass.ru/o-proekte/

**Comment by fruktoviy** [comment]
Follow The Compass is a music project started by a bass player Alexander Mukhin of Saint Petersburg, Russia in April 2012 when the debut album "First Flight" was released. All 8 pieces on the album were played solely on a Tune bass guitar by Alexander. Same year he was joined by Darya Pchelintseva on keyboard to fill the background of the music canvass sketched by the four-In July 2012 an EP Looking Forward was released.
By the end of the year the duo performed in Moscow and Saint-Petersburg.

In January 2014 Darya left and a new keyboard player Kseniya Besserebrennikova joined the project. Discovering new synergies led to the release of the FTC’s second album Imagination in July 2014.
This work revealed newly found colors, textures and musical instruments. It benefited from duo’s higher level of collaboration and Kseniya’s professional expertise in sound engineering.
At the end of 2014 and at the beginning of 2015 the band played two concerts in Saint Petersburg and Moscow to promote Imagination.

In 2015 the musicians started working on a new EP, which was later expanded to a full-length album titled Inside, released in April 2016. The sound became more meditative and experimental. The album cover art with a view inside a kaleidoscope meant to set listeners for a deeper mindful self-exploration

A cello player Valeriya (Lera) Stemasova joined the lineup on stage at the concerts to promote Inside. At the end of 2016 she performed with the band in the now customary venues in two Russian capital cities. Lera perfectly jelled on the old pieces and enhanced the sound of the new ones. In 2017 Lera was officially welcomed to the project as a permanent contributor.

Currently, FTC is working on the upcoming live performances and new music recordings.
·
И шапка:
Follow The Compass is a music project. Its intention is to expand the imagination and evoke various emotions, and sense of harmony and beauty of the inner and outer universe.

**Comment by fruktoviy** [comment]
Готово!

**Comment by TorinAsakura** [comment]
https://followthecompass.ru/en/
