### ISSUE TITLE
очередность релизов 

### ISSUE THREAD

**Issue by fruktoviy** [torin-asakura/ftc#24]
- создать инструмент редактирования релизами по очередности их появления

**Comment by TorinAsakura** [comment]
Сделал поле для установки порядка
<img width="2345" alt="Снимок экрана 2021-06-11 в 17 44 34" src="https://user-images.githubusercontent.com/3940885/121704734-b13b4700-cadc-11eb-88db-81341955c424.png">

**Comment by fruktoviy** [comment]
Попробую разобраться.
