### ISSUE TITLE
Разработка дизайна

### ISSUE THREAD

**Issue by TorinAsakura** [torin-asakura/ftc#3]
Тут поток сознания и прочие невнятные действия в отношение диза

**Comment by pianizator** [comment]
у меня созрела недурственная идея, по ftc . Покажу, как  будет понятный макет. У меня как-то сразу по нему видение открылось.

ну держи, поизучай мою мысль по ftc https://www.figma.com/file/3IdOdnv1EFnYRDT11QtlWN/FTC?node-id=0:1

Движение уровней ландшафта (звуковых волн) будет на зрителя. У пользователя  будет иллюзия движения вперед. Бесконечное следование. 

Скоро добавлю аниматики по главной, чтоб было понятней. 
По навигации ок, по лейблам подумаем, хочу избежать перекрытия обложки.

**Comment by TorinAsakura** [comment]
> у меня созрела недурственная идея, по ftc . Покажу, как будет понятный макет. У меня как-то сразу по нему видение открылось.
> 
> ну держи, поизучай мою мысль по ftc https://www.figma.com/file/3IdOdnv1EFnYRDT11QtlWN/FTC?node-id=0:1
> 
> Движение уровней ландшафта (звуковых волн) будет на зрителя. У пользователя будет иллюзия движения вперед. Бесконечное следование.
> 
> Скоро добавлю аниматики по главной, чтоб было понятней.
> По навигации ок, по лейблам подумаем, хочу избежать перекрытия обложки.

изучил, в целом почти как я и представлял, в частности мы почти полностью сошлись на параллакс эффекте на главной

единственное, что бросилось в глаза - лейблы на релизах, страшноваты, я бы сделал контрастирующего цвета геометрические объекты на самом объекте альбома (точку, ромб или типа того) и два цвета для сингла и альбома

**Comment by pianizator** [comment]
По навигации ок, по лейблам подумаем, хочу избежать перекрытия обложки. 

> единственное, что бросилось в глаза - лейблы на релизах, страшноваты, я бы сделал контрастирующего цвета геометрические объекты на самом объекте альбома (точку, ромб или типа того) и два цвета для сингла и альбома

**Comment by pianizator** [comment]
В итоге  сделал сразу кодом базовую анимацию ландшафта для главной. Запушить нет прав , код тут:
https://yadi.sk/d/fv7-YmG1CU7mGA

**Comment by TorinAsakura** [comment]
> В итоге  сделал сразу кодом базовую анимацию ландшафта для главной. Запушить нет прав , код тут:
> https://yadi.sk/d/fv7-YmG1CU7mGA

Отлично, концепт вполне годится, можем двигаться дальше

**Comment by pianizator** [comment]
Да я и не прекращал)
Высоту можем адаптивно регулировать, привязать к позиции мыши для большего эффекта  и цветовые схемы ("утро", "море", "лес" и тп) 
Разгребаю статику пока https://www.figma.com/file/3IdOdnv1EFnYRDT11QtlWN/FTC?node-id=0%3A1
По динамике вот такие будут моменты http://dogma7.com/ftc/cover/
http://dogma7.com/ftc/pointer/
> Отлично, концепт вполне годится, можем двигаться дальше

**Comment by pianizator** [comment]
а, вот еще, От процедурно-генерируемых волн отказался. Там надо кривыми Безье вырисовывать Лучше штук 10 svg которые можно еще зеркалить иногда  для пущей рандомности.

**Comment by TorinAsakura** [comment]
>а, вот еще, От процедурно-генерируемых волн отказался. Там надо кривыми Безье вырисовывать Лучше штук 10 svg которые можно еще зеркалить иногда  для пущей рандомности.

@pianizator ну, я тебе сразу про SVG говорил

**Comment by fruktoviy** [comment]
я многое пропустил судя по всему.. 
идея красивая и реализация

**Comment by TorinAsakura** [comment]
>я многое пропустил судя по всему..  ...

@fruktoviy ты ещё открой файлик index внутри архива (который на яндекс диске) и увидишь ещё чуть больше

**Comment by pianizator** [comment]
> ты ещё открой файлик index внутри архива (который на яндекс диске) и увидишь ещё чуть больше
или тут http://dogma7.com/ftc/main2/
PS скоро покажу оставшееся.

**Comment by fruktoviy** [comment]
ага, я видел) мне кажется такую анимацию нужно сделать чуть более медленной.

**Comment by pianizator** [comment]
Вот что у меня есть еще:
Статика там же https://www.figma.com/file/3IdOdnv1EFnYRDT11QtlWN/FTC?node-id=0%3A1
По динамике продолжая тему топографической геометрии и стрелки компаса собрал аниматики:

1)Появление превьюх видео, фото  и тп http://dogma7.com/ftc/photos-videos/
2)Появление релизов http://dogma7.com/ftc/music/ 
3)Появление контактов http://dogma7.com/ftc/contacts/   (футер как таковой прилепленный ко всем страницам я убрал и сделал страницу с контактами)

4)Ховеры на контактах (и аналогичные элементы) http://dogma7.com/ftc/contacts-hovers/
5)Ховер и клик главного меню http://dogma7.com/ftc/menu-hover/
6)По превью фото http://dogma7.com/ftc/photos-hover/
7)По видео http://dogma7.com/ftc/videos-hover/

8)«О проекте» есть идея подвязать анимацию к скроллу и сторителлингом подать
http://dogma7.com/ftc/about/

9)Если не будет напрягать то и появление на главной можно сделать аналогично
http://dogma7.com/ftc/main-maybe/  а потом заливка и движение

в чистовую на css с минимальным js без библиотек все реализуемо.

ну и раньше я делал ховер на релиз http://dogma7.com/ftc/cover/
и главный логотип http://dogma7.com/ftc/pointer/


Если сервак будет тупить, на диске дублирую —  https://yadi.sk/d/fv7-YmG1CU7mGA

По скорости анимации на главной  - это все будет еще настраиваться. + я хотел там еще поиграться с дополнительными штуками.

**Comment by pianizator** [comment]
Забирай  макеты из фигмы на верстку. Если какие-то элементы понадобятся — добавлю или в макет или кодом.

**Comment by pianizator** [comment]
Добавил блок анонса как я его вижу https://www.figma.com/file/3IdOdnv1EFnYRDT11QtlWN/FTC?node-id=0%3A1
