### ISSUE TITLE
Раздел релизы

### ISSUE THREAD

**Issue by fruktoviy** [torin-asakura/ftc#7]
@TorinAsakura Привет. Обновленный сайт смотрится хорошо!) Хотел чтобы ты немного изменил раздел 'релизы'. То есть.. сейчас альбомы сверху старые, а надо наоборот сделать, сверху вниз - от новых к старым
![pVWwJ5EClgE](https://user-images.githubusercontent.com/55533678/84578566-20e5fb80-adcf-11ea-8692-75d47116454f.jpg)

**Comment by TorinAsakura** [comment]
https://followthecompass.ru/category/relizy/
