### ISSUE TITLE
Правки по сайту

### ISSUE THREAD

**Issue by fruktoviy** [torin-asakura/ftc#8]
1) в шапке раздела "релизы" указан правильный порядок выхода альбомов и синглов. а если кликнуть и зайти в этот раздел, то порядок становится неправильным. А также на главной странице раздел "Последние релизы" - там тоже неправильный порядок релизов

2) в разделе "о проекте" в рус версии нужно удалить последнее предложение - "На данный момент музыканты готовят обновленную программу для выступлений." 

3) Внизу страниц столбец "LISTEN" надо Google Play заменить на YouTube Music

**Comment by TorinAsakura** [comment]
1. Увы, так как они паблились в один год то сортируются алфавитно, я теперь не могу управлять их порядком, они приходят с админки, не думаю, что это так важно Сань
2. Готово
3. Футера больше не будет
