### ISSUE TITLE
[request] Адреса локаций

### ISSUE THREAD

**Issue by TorinAsakura** [torin-asakura/ftc#9]
Для новой страницы **Контакты**, которая призвана избавить нас от безобразного футера, нужно собрать все адреса где светился FTC, я сделаю интерактивную карту с картинками, просто красивый декор.

Места концертов.
Места записи.
Места съёмок.

**Comment by fruktoviy** [comment]
Концерты:
12.12.12 - China Town Cafe (Москва, Лубянский проезд, 25, стр. 1)
21.12.12 - Китайский Летчик Джао Да (Санкт-Петербург, ул. Пестеля, 7)
20.04.13 - Манхэттен (Санкт-Петербург, Набережная Реки Фонтанки 90к1)
24.10.14 - Grrr Jamming Squeak (Санкт-Петербург, Лиговский просп., д. 73)
21.11.14 - Биржа Бар (Санкт-Петербург, Биржевой пер., 4)
28.02.15 - Китайский Летчик Джао Да (Москва, Лубянский пр-д, 25с1)
26.11.16 - Вермель (Москва, Раушская наб., 4)
02.12.16 - Арт-Мансарда 4'33 (Санкт-Петербург, Биржевой пер. д. 4)

Студии звукозаписи: 

RED~WAVE - Санкт-Петербург. проспект Старо-Петергофский д.44 (Colors)
Galernaya 20 - Санкт-Петербург Галерная улица, 20-22Б (Inside, Return, Colors)
Библиотека Им - Санкт-Петербург Казанская 7 (Imagination)
(остальное записано дома)

Места съёмок:

July Syn - Парк 300 летия санкт петербург (делали сами)
One Moment - Финский залив (Camera, Edited - Михаил Сиднин https://vk.com/msidnin)
Return - Центр Санкт-Петербурга ( съемка oneskypro)
Colors - Греция (Camera, Edited - Михаил Сиднин(https://vk.com/msidnin), Материалы из архива - https://silavetra.com/)

**Comment by TorinAsakura** [comment]
Пока не нашёл применения данному контенту, но, страницу контактов сделал https://followthecompass.ru/kontakty/
